version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint
    versions:
    - 4.19.1
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: faker
    versions:
    - 5.2.0
    - 5.3.1
    - 5.4.0
    - 5.5.0
    - 5.5.1
    - 5.5.2
  - dependency-name: sinon
    versions:
    - 10.0.0
    - 9.2.4
  - dependency-name: sequelize
    versions:
    - 6.4.0
    - 6.5.0
    - 6.5.1
    - 6.6.1
  - dependency-name: dotenv-webpack
    versions:
    - 6.0.0
    - 6.0.2
    - 6.0.4
    - 7.0.1
  - dependency-name: jquery
    versions:
    - 3.5.1
